/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.block;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlockStandaloneSetup extends BlockStandaloneSetupGenerated {

	public static void doSetup() {
		new BlockStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
