/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hello;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HelloRuntimeModule extends AbstractHelloRuntimeModule {
}
