/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hellogenn;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HelloGenStandaloneSetup extends HelloGenStandaloneSetupGenerated {

	public static void doSetup() {
		new HelloGenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
