/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hello.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class HelloOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
