/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hex.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HexUiModule extends AbstractHexUiModule {

	public HexUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
