/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hellogenn.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.idiomaticsoft.dsl.hellogenn.HelloGenRuntimeModule;
import com.idiomaticsoft.dsl.hellogenn.HelloGenStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HelloGenIdeSetup extends HelloGenStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloGenRuntimeModule(), new HelloGenIdeModule()));
	}
	
}
