/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hellogenn.ide;


/**
 * Use this class to register ide components.
 */
public class HelloGenIdeModule extends AbstractHelloGenIdeModule {
}
