/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hello.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HelloUiModule extends AbstractHelloUiModule {

	public HelloUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
