/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hex;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HexRuntimeModule extends AbstractHexRuntimeModule {
}
