/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.block.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.idiomaticsoft.dsl.block.BlockRuntimeModule;
import com.idiomaticsoft.dsl.block.BlockStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BlockIdeSetup extends BlockStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BlockRuntimeModule(), new BlockIdeModule()));
	}
	
}
