/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hex;

import org.eclipse.xtext.conversion.IValueConverterService;

import com.idiomaticsoft.dsl.hex.converter.MyValueConverter;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class HexRuntimeModule extends AbstractHexRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MyValueConverter.class;
	}

}
