/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hex;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HexStandaloneSetup extends HexStandaloneSetupGenerated {

	public static void doSetup() {
		new HexStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
