/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.idiomaticsoft.dsl.hex.HexRuntimeModule;
import com.idiomaticsoft.dsl.hex.HexStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HexIdeSetup extends HexStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HexRuntimeModule(), new HexIdeModule()));
	}
	
}
