/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.hellogenn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HelloGenUiModule extends AbstractHelloGenUiModule {

	public HelloGenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
