/*
 * generated by Xtext 2.26.0
 */
package com.idiomaticsoft.dsl.block.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BlockUiModule extends AbstractBlockUiModule {

	public BlockUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
