grammar com.idiomaticsoft.dsl.block.Block with org.eclipse.xtext.common.Terminals

generate block "http://www.idiomaticsoft.com/dsl/block/Block"

Model:
	blocks+=Block*;

Import:
	'import' importedNamespace=ImportFQN;

Block:
	'block' name=ID '{'
	(imports+=Import)*
	(members+=Member)*
	'}';

Member:
	Block | Field | Alias;

Field:
	'field' name=ID;

Alias:
	'alias' name=ID 'aliases' alias=[Member|MemberFQN];

MemberFQN:
	ID ("." ID)*;

ImportFQN:
	ID ("." ID)* ('.' (ID | '*'));